#!/bin/bash -e
# shows changes in recently installed gems

if sed --version 2>&1 | head -1 | grep ^GNU > /dev/null
then
	ESED="sed --regexp-extended"
else
	ESED="sed -E"
fi

gem environment gempath | sed 's/:/\n/g' | while read GEMPATH_DIR
do
	find "$GEMPATH_DIR/gems" -maxdepth 1 -depth 1 -type d -mtime -12h -exec basename {} \; | $ESED 's/-[0-9.]+$//' | sort | uniq | while read GEMNAME
	do
		
		set -f # disable globbing
		IFS=$'\n' # split on newlines
		gem_version_paths=( $( find "$GEMPATH_DIR/gems" -maxdepth 1 -depth 1 -type d -name "${GEMNAME}-[0-9]*" -exec ls -1dtr {} + | tail -2 ) )
		unset IFS # reset to default line separator
		set +f # re-enable globbing
		
		if [ "${#gem_version_paths[@]}" -eq 2 ]
		then
			
			IFS=$'\n' # split on newlines
			gem_version_paths_str=$( echo "${gem_version_paths[*]}" )
			unset IFS # reset to default line separator
			gem_versions=( $( echo "$gem_version_paths_str" | xargs -n 1 basename | egrep -o '([0-9.]+)$' ) )
			
			if which chdiff 2> /dev/null >&2
			then
				echo "$GEMNAME updated from ${gem_versions[0]} to ${gem_versions[1]}"
				chdiff --background "${gem_version_paths[0]}" "${gem_version_paths[1]}"
			else
				{
					echo "$GEMNAME updated from ${gem_versions[0]} to ${gem_versions[1]}"
					echo
					diff -br "${gem_version_paths[0]}" "${gem_version_paths[1]}" | diffstat
					echo
					if which colordiff 2> /dev/null >&2
					then
						DIFF=colordiff
					else
						DIFF=diff
					fi
					$DIFF -br -U 4 "${gem_version_paths[0]}" "${gem_version_paths[1]}"
				} | less -rK
			fi
			
		fi
		
	done
done
