#!/bin/bash -e
if sw_vers -productVersion | grep -q '^10\.[1-5]\.'
then
	for FILE in "$@"
	do
		FILE="`readlink -f "$FILE"`"
		osascript \
			-e 'tell application "Finder"' \
			-e '	reveal POSIX file "'"$FILE"'"' \
			-e '	activate' \
			-e 'end tell' > /dev/null
	done
else
	open -R -- "$@"
fi
