#!/bin/bash -e

# for this script to be useful you'll want something like this in your ~/.ssh/config:
#   Host *
#     ControlPath /Users/jason/.ssh/control/%r@%h:%p


if /usr/bin/ssh -O check "$@" 2> /dev/null > /dev/null
then
	true # all good
else
	/usr/bin/ssh -MNfX "$@"
	sleep 1
fi
exec /usr/bin/ssh "$@"
