set guioptions-=T " Hide the tool bar

" MacVim
if has("gui_macvim")
  set guifont=Monaco:h16

  " Disable scrollbars
  set guioptions-=rL

  " Disable MacVim keybindings
  macmenu &Edit.Find.Find\.\.\. key=<nop>
  nmap <D-f> <Esc>
  nmap <D-F> <Esc>
  macmenu &File.New\ Tab key=<nop>
  nmap <D-t> <Esc>
  macmenu &File.Open\ Tab\.\.\. key=<nop>
  nmap <D-T> <Esc>
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>

  " Cmd+W to close current buffer and close the window if no buffers are left
  macmenu &File.Close key=<nop>
  nmap <D-w> :CommandW<CR>
  imap <D-w> <Esc>:CommandW<CR>

  " Disable Cmd+S to encourage `:w`
  macmenu &File.Save key=<nop>
  map <D-s> <Esc>
  imap <D-s> <Esc><Esc>i
endif

" Cursor
set guicursor=a:blinkon0 " turn off cursor blink
set guicursor+=i:ver25-iCursor " colour cursor in insert mode
set guicursor+=c:block-cCursor " colour cursor in command mode

" Color columns
hi ColorColumn guibg=#F0F0F0
