Bundle 'bufkill.vim'
Bundle 'nathanaelkane/vim-command-w'
Bundle 'Soares/butane.vim'
Bundle 'dterei/VimBookmarking'
Bundle 'godlygeek/tabular'
Bundle 'tomtom/tcomment_vim'
Bundle 'sjl/gundo.vim'
Bundle 'ervandew/supertab'
Bundle 'sickill/vim-pasta'
Bundle 'bkad/CamelCaseMotion'
Bundle 'twe4ked/vim-diff-toggle'
Bundle 'AndrewRadev/linediff.vim'
Bundle 'bogado/file-line'

Bundle 'nanotech/jellybeans.vim'
Bundle 'bclear'
Bundle 'rdark'
Bundle 'nelstrom/vim-mac-classic-theme'
